# Generated by Django 2.1.4 on 2019-04-21 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20190414_1904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='categorie',
            field=models.CharField(choices=[('alimento', 'Alimento'), ('objeto', 'Objeto'), ('bebida', 'Bebida'), ('golosina', 'Golosina')], max_length=50, verbose_name='Categoria'),
        ),
    ]
