# Generated by Django 2.1.4 on 2019-04-14 22:32

from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='presentation',
            field=models.ImageField(default=1, upload_to=products.models.upload_image_of_product, verbose_name='Presentacion'),
            preserve_default=False,
        ),
    ]
