# Generated by Django 2.1.4 on 2019-04-14 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_productmodel_presentation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='categorie',
            field=models.CharField(choices=[('alimento', 'Alimento'), ('objeto', 'Objeto')], max_length=50, verbose_name='Categoria'),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='description',
            field=models.TextField(),
        ),
    ]
